### ISSUE TITLE
Close the dropdown on apply

### ISSUE THREAD

**Issue by Assafkalfa** [maufarinelli/react-multiselect-dropdown-button#40]
Hello, sorry I'm harassing you

Can we close the dropdown div on clicking on Apply button?

Thank you!!

**Comment by ksagar09** [comment]
Hey.. Have you got any clue?

**Comment by maufarinelli** [comment]
Hi @ksagar09 . I am planning to do a real refactoring on it pretty soon (missing time for that). Then I will add this feature as well

**Comment by maufarinelli** [comment]
@Assafkalfa and @ksagar09 , I have just merged https://github.com/maufarinelli/react-multiselect-dropdown-button/pull/47
enabling this functionality (close dropdown on apply) 
See the `closeDropdownOnApply` in the README
Available in the latest version v2.0.1
I hope it help you guys. Cheers
